[features]
seeds = false
skip-lint = false
[programs.devnet]
sol_twitter = "ECj8sRDTpoGS7o71Tu9QC24sRsMWeqkzeJpxWozSbWxP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/gkvkrypto/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
